import { makeStyles } from '@material-ui/core'

export const useStyles = makeStyles((theme) => ({
	[theme.breakpoints.down('sm')]: {
		root: {
			flexDirection: 'column',
			alignItems: 'center',
			background: theme.palette.background.paper,
		},
		header: {
			color: theme.palette.primary.main,
			marginTop: '20%',
		},
		contactBy: {
			textDecoration: 'none',
			fontSize: '1.4em',
			color: theme.palette.background.paper,
			fontWeight: '500',
			background: theme.palette.primary.main,
			padding: '.5em',
		},
		bottomNav: {
			marginTop: '10%',
			marginBottom: '10%',
			background: theme.palette.primary.main,
			border: `.1em solid ${theme.palette.primary.light}`,
			height: 'auto',
			borderRadius: '.4em',
		},
		jumper: {
			marginBottom: '10%',
			textDecoration: 'none',
			background: theme.palette.primary.main,
			color: theme.palette.background.paper,
			width: '30vw',
			textAlign: 'center',
			borderRadius: '1vw',
		},
		iconWrapper: {
			color: theme.palette.background.paper,
		},
		icon: { fontSize: '7vw' },
		info: { background: theme.palette.primary.main },
		name: { color: theme.palette.text.primary },
		modal: {
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'center',
		},
		resume: {
			display: 'block',
			width: '95%',
			margin: '0 auto',
		},
	},

	[theme.breakpoints.between('sm', 'md')]: {
		root: {
			flexDirection: 'column',
			alignItems: 'center',
			background: theme.palette.background.paper,
		},
		header: {
			color: theme.palette.primary.main,
			marginTop: '20%',
			fontSize: '4.5vw',
		},
		contactBy: {
			textDecoration: 'none',
			fontSize: '3.5vw',
			color: theme.palette.background.paper,
			fontWeight: '500',
			background: theme.palette.primary.main,
			padding: '.3em',
		},
		bottomNav: {
			marginTop: '10%',
			marginBottom: '10%',
			background: theme.palette.primary.main,
			border: `.1em solid ${theme.palette.primary.light}`,
			height: 'auto',
			width: '50vw',
			borderRadius: '.4em',
		},
		jumper: {
			marginBottom: '10%',
			textDecoration: 'none',
			background: theme.palette.primary.main,
			color: theme.palette.background.paper,
			width: '15vw',
			textAlign: 'center',
			borderRadius: '1vw',
		},
		iconWrapper: {
			color: theme.palette.background.paper,
		},
		icon: { fontSize: '7vw' },
		info: { background: theme.palette.primary.main },
		name: {
			color: theme.palette.text.primary,
			fontSize: '4vw',
			marginBottom: '5vw',
		},
		resume: {
			display: 'block',
			height: '50%',
			margin: '0 auto',
		},
	},

	[theme.breakpoints.between('md', 'lg')]: {
		root: {
			flexDirection: 'column',
			alignItems: 'center',
			background: theme.palette.background.paper,
		},
		header: {
			color: theme.palette.primary.main,
			marginTop: '20%',
			fontSize: '4vw',
		},
		contactBy: {
			textDecoration: 'none',
			fontSize: '1.5vw',
			color: theme.palette.background.paper,
			fontWeight: '500',
			background: theme.palette.primary.main,
			padding: '.3em',
			borderRadius: '.3em',
		},
		bottomNav: {
			marginTop: '5%',
			marginBottom: '10%',
			background: theme.palette.primary.main,
			border: `.1em solid ${theme.palette.primary.light}`,
			height: 'auto',
			width: '40vw',
			borderRadius: '.4em',
			justifyContent: 'space-evenly',
		},
		jumper: {
			marginBottom: '5%',
			textDecoration: 'none',
			background: theme.palette.primary.main,
			color: theme.palette.background.paper,
			width: '7vw',
			textAlign: 'center',
			borderRadius: '1vw',
			fontSize: '1vw',
		},
		iconWrapper: {
			color: theme.palette.background.paper,
		},
		icon: { fontSize: '5vw' },
		info: { background: theme.palette.primary.main },
		name: {
			color: theme.palette.text.primary,
			fontSize: '4vw',
			marginBottom: '5vw',
		},
		resume: {
			position: 'absolute',
			width: '38vw',
			top: '1vw',
			left: '31vw',
		},
	},

	[theme.breakpoints.up('xl')]: {
		root: {
			flexDirection: 'column',
			alignItems: 'center',
			background: theme.palette.background.paper,
		},
		header: {
			color: theme.palette.primary.main,
			marginTop: '20%',
			fontSize: '4vw',
		},
		contactBy: {
			textDecoration: 'none',
			fontSize: '1.5vw',
			color: theme.palette.background.paper,
			fontWeight: '500',
			background: theme.palette.primary.main,
			padding: '.3em',
			borderRadius: '.3em',
		},
		bottomNav: {
			marginTop: '5%',
			marginBottom: '10%',
			background: theme.palette.primary.main,
			border: `.1em solid ${theme.palette.primary.light}`,
			height: 'auto',
			width: '40vw',
			borderRadius: '.4em',
			justifyContent: 'space-evenly',
		},
		jumper: {
			marginBottom: '5%',
			textDecoration: 'none',
			background: theme.palette.primary.main,
			color: theme.palette.background.paper,
			width: '7vw',
			textAlign: 'center',
			borderRadius: '1vw',
			fontSize: '1vw',
		},
		iconWrapper: {
			color: theme.palette.background.paper,
		},
		icon: { fontSize: '5vw' },
		info: { background: theme.palette.primary.main },
		name: {
			color: theme.palette.text.primary,
			fontSize: '4vw',
			marginBottom: '5vw',
		},
		resume: {
			position: 'absolute',
			width: '38vw',
			top: '1vw',
			left: '31vw',
		},
	},
}))
